### ISSUE TITLE
About license

### ISSUE THREAD

**Issue by maruilian11** [sachinchoolur/lg-video#1]
Hi, I just sent a PR to add this lib to cdnjs. Just want to confirm the license with you.
I saw `GPLv3` in [package.json](https://github.com/sachinchoolur/lg-video/blob/master/package.json#L24), but `AGPLv3` in [LICENSE.md](https://github.com/sachinchoolur/lg-video/blob/master/LICENSE.md).

https://github.com/cdnjs/cdnjs/issues/9087
https://github.com/cdnjs/cdnjs/pull/11404

**Comment by sachinchoolur** [comment]
Hi @maruilian11 ,
Thank you for considering hosting lightGallery on cdnjs. lightGallery and its submodules are licensed under GPLv3 license. I'll update the docs ASAP
