### ISSUE TITLE
No cover will have wrong behavior

### ISSUE THREAD

**Issue by anran758** [sachinchoolur/lg-video#10]
Hello, when I use the plugin, I find that if a cover is empty, then his neighbor will automatically play this video.

You can see this demo. When you click on the second or fourth video, the content of the third video will be played automatically.

https://codepen.io/anran758/pen/jooeLe?editors=1100

**Comment by sachinchoolur** [comment]
In the codepen demo you are using the vanilla js version of [lg-video](https://github.com/sachinchoolur/lg-video.js) plugin.

This was fixed in the jQuery version a long time ago. But I missed it in the vanilla js version.

It is fixed in the latest version. Thank you for pointing this out
