### ISSUE TITLE
Insecure Iframe on https pages

### ISSUE THREAD

**Issue by grzegorz-s** [sachinchoolur/lg-video#2]
Because of an iframe with http link, there is an issue with Active Mixed Content on https webpages. Is there any chance you to change url from http to https within file lg-video.js?

`video = '<iframe class="lg-video-object lg-vk ' + addClass + '" width="560" height="315" src="http://vk.com/video_ext.php?' + isVideo.vk[1] + a + '" frameborder="0" allowfullscreen></iframe>';`

**Comment by sachinchoolur** [comment]
Hey @grzegorz-s ,

The issue has been fixed. Please use the letest version of lightGallery.
