### ISSUE TITLE
No vanilla option available?

### ISSUE THREAD

**Issue by mxmtsk** [sachinchoolur/lg-video#9]
Is there a non jQuery-Version of the Video Plugin available?

I was seeing documentation for it on the vanilla-js version documentation:
https://sachinchoolur.github.io/lightgallery.js/docs/api.html#lg-video

I was only able to find this plugin - but it seems to be written in jQuery.

Also, I was trying to get it to work with ES6 imports (just like with the lightgallery script).
When writing `import 'lg-video';` however the console throws an error:

```
lg-video.js:338 Uncaught TypeError: Cannot read property 'modules' of undefined
```

**Comment by sachinchoolur** [comment]
Really sorry for the late reply. 
Vanilla version is already available - https://github.com/sachinchoolur/lg-video.js 

And the package name is '[lg-video.js](https://www.npmjs.com/package/lg-video.js)' not `lg-video`.
I think that is why you are getting the console error  
```
import 'lg-video.js'
```
